---
title: "Les nouveautés de l'écosystème {torch}"
author:
  - Christophe Regouby^[Airbus S.A.S., christophe.regouby@airbus.com]
format: typst
indent: true
lang: fr
---

```{=typst}
#align(center)[#strong[Résumé (max 300 mots)]]
```
L’univers des packages {torch}, le « mlverse », s’est enrichi durant l’année écoulée grâce à des améliorations considérables des packages historiques, une expansion vers de nouveaux domaines métiers et une adoption croissante par la communauté. Je vous présenterai toute cette richesse lors d'une conférence courte, en démontrant à quel point les échanges lors des précédentes Rencontres R ont favorisé cette expansion. Une véritable invitation à se rencontrer, collaborer et contribuer.

**Mots-clefs (3 à 5)** : Apprentissage profond - Torch - IA - Package - Écosystème R

## Développement

La présentation fera le point sur les nouveautés de **{torch}**, le package pivot de l’univers, ainsi que sur les améliorations de la documentation pour l’installation et la prise en main.

L’accent sera également mis sur les nouveautés du package **{torchvision}** : les nouveaux jeux de données d’images et les domaines métiers couverts (écologie, industrie, biologie marine, etc.). Ces avancées, notamment initiées lors des Rencontres R 2024, incluent également de nombreux nouveaux modèles de classification, de détection d'objet ou de segmentation, fruits du travail de deux contributeurs du GSoC 2025.

La nouvelle version de **{tabnet}** sera également abordée. Elle intègre désormais une fonction de perte dédiée aux classificateurs binaires déséquilibrés qui, comme le montre une vignette détaillée, permet d'obtenir une aire sous la courbe (AUC) supérieure à celle de XGBoost. Cette évolution est le résultat direct des échanges tenus lors des Rencontres R 2025.

Enfin, le reste de l’écosystème ne sera pas en reste, avec l’évocation de l’intégration des réseaux de neurones sur graphes (**Graph Neural Networks**) et des **modèles de survie**.

------------------------------------------------------------------------
